CREATE TABLE ponto.log_auditoria (
    id bigint generated by default as identity primary key,
    evento varchar(255) not null,
    entidade text not null,
    usuario_logado varchar(200) not null,
    data_ocorrencia timestamp without time zone
);