CREATE TABLE ponto.operacao_log_auditoria (
    id smallint generated by default as identity primary key,
    descricao varchar(50) not null
);

insert into ponto.operacao_log_auditoria (descricao) values ('INCLUSÃO');